import {describe,it,expect} from 'vitest';
import {decodeStopLink,encodeStopLink,decodeTripLink,encodeTripLink,parseTripFile,serializeTrip,validateTrip,tripRoute,tripHref,readTrips,writeTrips,type Trip} from '../src/trips';
import {tours} from '../src/tour';
const trip:Trip={version:1,title:'A sky full of ✨',stops:[{id:'first',kind:'place',route:'road-trip',stop:'andromeda',note:'Look at the dust.'},{id:'second',kind:'view',name:'Our perspective 🌌',hash:'#t=0,0,0&c=0,0,1&g=sun'}]};
describe('shared itineraries',()=>{
 it('round trips exact Unicode through file and URL codecs',()=>{expect(decodeTripLink(encodeTripLink(trip)!)).toEqual(trip);expect(parseTripFile(serializeTrip(trip)!)).toEqual(trip)});
 it('accepts only known versioned paused stop links',()=>{for(const t of tours)for(const s of t.stops)expect(decodeStopLink(encodeStopLink(t.key,s.id)!)).toEqual({route:t.key,stop:s.id});for(const hash of ['#stop=2:road-trip:andromeda','#stop=1:road-trip:nope','#stop=1:road-trip:andromeda&x=1','#stop=1:ROAD-TRIP:andromeda'])expect(decodeStopLink(hash)).toBeNull()});
 it('rejects malformed versions, unknown fields, duplicates and untrusted view grammar',()=>{
  for(const value of [{...trip,version:2},{...trip,extra:'x'},{...trip,stops:[]},{...trip,stops:[trip.stops[0],trip.stops[0]]},{...trip,title:'\ud800'},{...trip,title:'bad\u0000'},{...trip,stops:[{...trip.stops[0],stop:'made-up'}]},{...trip,stops:[{...trip.stops[1],hash:'javascript:alert(1)'}]},{...trip,stops:[{...trip.stops[1],hash:'#t=0,0,0&c=0,0,1&x=1'}]},{...trip,stops:[{...trip.stops[1],hash:'#t=0,0,0&c=0,0,1&c=0,0,2'}]}])expect(validateTrip(value)).toBeNull();
  for(const value of ['#trip=2.aaaa','#trip=1._w','#trip=1.e30=','#trip=1.e30','#trip=1.'+'x'.repeat(8001)])expect(decodeTripLink(value)).toBeNull();
 });
 it('bounds Unicode by characters and offers files for valid trips too long for a URL',()=>{
  const long:Trip={version:1,title:'🌌'.repeat(60),stops:Array.from({length:10},(_,i)=>({id:'s'+i,kind:'view',name:'🌌'.repeat(60),note:'🌌'.repeat(180),hash:'#t=0,0,0&c=0,0,1'}))};expect(validateTrip(long)).not.toBeNull();expect(encodeTripLink(long)).toBeNull();expect(parseTripFile(serializeTrip(long)!)).toEqual(long);expect(tripHref(trip,'https://example.org/'+ 'x'.repeat(8000))).toBeNull();expect(parseTripFile(' '.repeat(65537))).toBeNull();expect(validateTrip({...trip,title:'🌌'.repeat(61)})).toBeNull();expect(validateTrip({...trip,stops:[{...trip.stops[0],note:'🌌'.repeat(181)}]})).toBeNull();expect(validateTrip({...trip,stops:Array.from({length:11},(_,i)=>({...trip.stops[0],id:'s'+i}))})).toBeNull();
 });
 it('retains source captions independently of creator notes and preserves saved camera targets',()=>{const route=tripRoute(trip);expect(route.stops[0].caption).toBe(tours.find(t=>t.key==='road-trip')!.stops.find(s=>s.id==='andromeda')!.caption);expect(route.stops[0].note).toBe('Look at the dust.');expect(route.stops[0].sourceStop).toEqual({route:'road-trip',id:'andromeda'});expect(route.stops[1].target.view).toEqual({target:[0,0,0],camera:[0,0,1],identity:'sun'});expect(route.stops.map(s=>s.id)).toEqual(['first','second'])});
 it('retains plain markup as text without interpreting it or allowing schema extensions',()=>{expect(validateTrip({...trip,title:'<img src=x onerror=alert(1)>'})?.title).toContain('<img');expect(parseTripFile('{"version":1,"title":"x","stops":[],"__proto__":{}}')).toBeNull()});
 it('normalizes public identities without serializing dense internal IDs',()=>{const exact={...trip,stops:[{id:'view',kind:'view',name:'DESI',hash:'#t=1,2,3&c=.1,0,0&g=desi:512:10:39633325333155389'}]};expect(validateTrip(exact)).toBeNull();exact.stops[0].hash=exact.stops[0].hash.replace('c=.1','c=0.1');expect(validateTrip(exact)?.stops[0]).toEqual(exact.stops[0]);expect(validateTrip({...trip,stops:[{...exact.stops[0],id:'42',denseId:42}]})).toBeNull()});
 it('bounds local persistence and handles inaccessible or corrupt storage',()=>{
  let raw='';const storage={getItem:()=>raw,setItem:(_:string,value:string)=>{raw=value}};expect(writeTrips(storage,[{id:'a',trip}])).toBe(true);expect(readTrips(storage)).toEqual([{id:'a',trip}]);expect(writeTrips(storage,Array.from({length:11},(_,i)=>({id:'a'+i,trip})))).toBe(false);expect(writeTrips(storage,[{id:'a',trip},{id:'a',trip}])).toBe(false);raw='broken';expect(readTrips(storage)).toEqual([]);expect(readTrips({getItem:()=>{throw Error('blocked')}})).toEqual([]);expect(writeTrips({setItem:()=>{throw Error('full')}},[{id:'a',trip}])).toBe(false);raw='x'.repeat(660000);expect(readTrips(storage)).toEqual([]);
 });
});
