/** Shared-stop and custom-itinerary journeys through production controls and real browser navigation. */
import {mkdir,writeFile,readFile} from 'node:fs/promises';
import {execFileSync} from 'node:child_process';
import {pathToFileURL} from 'node:url';
import assert from 'node:assert/strict';
const {chromium,webkit}=await import(process.env.PLAYWRIGHT_MODULE?pathToFileURL(process.env.PLAYWRIGHT_MODULE).href:'playwright');
const base=process.env.ATLAS_TEST_URL??'http://127.0.0.1:4180/',dir=process.env.ATLAS_TEST_OUTPUT??'.cache/trip-ui';await mkdir(dir,{recursive:true});
const report={runId:'trip-ui',sourceCommit:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),checks:{},errors:[],status:'running'};
let scope='',active;const check=(name,value)=>{report.checks[`${scope}:${name}`]=value;assert.ok(value,`${scope}:${name}`)};
const progress=setInterval(()=>console.log(scope,Object.keys(report.checks).length),30000);
const hash=trip=>'#trip=1.'+Buffer.from(JSON.stringify(trip)).toString('base64url');
try{
 for(const engine of (process.env.ATLAS_TRIP_ENGINES??'chrome,webkit').split(',')){
  scope=engine;const mobile=engine==='webkit',browser=await(mobile?webkit.launch({headless:true}):chromium.launch({channel:'chrome',headless:true}));
  const options={viewport:mobile?{width:402,height:874}:{width:1600,height:1000},hasTouch:mobile,isMobile:mobile,reducedMotion:'reduce',acceptDownloads:true};
  const create=async()=>{const p=await browser.newPage(options);active=p;p.on('pageerror',e=>report.errors.push(e.message));await p.addInitScript(()=>{window.__atlasTools={};Object.defineProperty(document,'modelContext',{value:{registerTool(t){window.__atlasTools[t.name]=t.execute}}});Object.defineProperty(navigator,'clipboard',{value:{writeText:()=>Promise.reject(Error('clipboard blocked'))}})});return p};
  const ready=p=>p.waitForFunction(()=>!document.getElementById('visit-galaxy-button').hidden),state=p=>p.evaluate(()=>window.__atlasTools.read_atlas_view({}));
  const arrived=p=>p.waitForFunction(()=>/^(Paused|Arrived|Partial)/.test(document.getElementById('tour-status').textContent),null,{timeout:30000});
  const share=async p=>{if(!await p.locator('#share-button').isVisible())await p.click('#mobile-menu-button');await p.click('#share-button')};
  const creator=await create();
  try{
   await creator.goto(base);await ready(creator);const initial=(await state(creator)).link;
   await share(creator);await creator.fill('#view-name','Saved survey view');await creator.click('#save-view-button');await creator.click('#my-trips-button');
   await creator.fill('#trip-title','Our sky 🌌');await creator.selectOption('#trip-source','road-trip:andromeda');await creator.click('#trip-add');await creator.selectOption('#trip-source','road-trip:lmc');await creator.click('#trip-add');
   await creator.locator('#trip-stops > li').first().locator('[data-action=down]').click();await creator.locator('#trip-stops textarea').first().fill('Look for the bar. <b>My note</b> ✨');await creator.selectOption('#trip-source','view:0');await creator.click('#trip-add');
   check('addedSavedView',await creator.locator('#trip-stops > li').count()===3);await creator.click('#trip-current');check('addedCurrentView',await creator.locator('#trip-stops > li').count()===4);await creator.locator('#trip-stops > li').last().locator('[data-action=remove]').click();
   await creator.click('#trip-save');check('savedLocally',(await creator.locator('#trip-status').textContent()).includes('saved in this browser'));
   const stored=await creator.evaluate(()=>JSON.parse(localStorage.getItem('atlas-custom-trips')).trips[0].trip);check('orderAndNotePersisted',stored.stops[0].stop==='lmc'&&stored.stops[0].note.includes('<b>')&&stored.stops[2].hash===initial);
   await creator.reload();await ready(creator);await creator.click('#tours-button');await creator.click('#create-trip-button');await creator.click('#trip-saved [data-action=open]');check('reopenedFromStorage',await creator.inputValue('#trip-title')==='Our sky 🌌'&&await creator.locator('#trip-stops > li').count()===3);
   await creator.click('#trip-copy');await creator.waitForSelector('#trip-link:visible');const url=await creator.inputValue('#trip-link');check('clipboardFallback',url.includes('#trip=1.'));
   const downloadEvent=creator.waitForEvent('download');await creator.click('#trip-export');const download=await downloadEvent,exportPath=`${dir}/${engine}-trip.json`;await download.saveAs(exportPath);check('exportMatches',JSON.parse(await readFile(exportPath,'utf8')).title==='Our sky 🌌');
   for(const [layout,width,height]of [['portrait',402,874],['landscape',874,402],['desktop',1600,1000]]){await creator.setViewportSize({width,height});await creator.waitForTimeout(120);await creator.locator('#trip-close').scrollIntoViewIfNeeded();const b=await creator.locator('#trip-dialog').boundingBox();check(`${layout}:bounded`,b.x>=0&&b.y>=0&&b.x+b.width<=width+1&&b.y+b.height<=height+1);await creator.screenshot({path:`${dir}/${engine}-${layout}-editor.png`})}
   await creator.click('#trip-preview');check('previewPlainText',await creator.locator('#trip-itinerary').textContent().then(t=>t.includes('<b>My note</b>'))&&await creator.locator('#trip-itinerary :is(b,img,script)').count()===0);await creator.click('#trip-edit');await creator.click('#trip-saved [data-action=delete]');check('deleteLocal',await creator.locator('#trip-saved li').count()===0);
   // The recipient is a fresh browser context with no local saved trips.
   const recipient=await create();await recipient.goto(url);await ready(recipient);await recipient.waitForSelector('#trip-recipient:visible');check('recipientPreview',await recipient.locator('#trip-preview-title').textContent()==='Our sky 🌌'&&(await state(recipient)).tour===null);check('linkConsumed',await recipient.evaluate(()=>location.hash===''));
   const before=(await state(recipient)).link;await recipient.waitForTimeout(9000);check('previewNeverAutoplays',(await state(recipient)).link===before&&(await state(recipient)).tour===null);await recipient.click('#trip-start');await arrived(recipient);await recipient.click('#tour-play');check('customFirstDestination',(await state(recipient)).selected.targetId==='nearby:lmc'&&(await state(recipient)).tour.key==='custom');
   check('separateCreatorNote',(await recipient.locator('#tour-user-note').textContent()).includes('<b>My note</b>')&&!(await recipient.locator('#tour-caption').textContent()).includes('My note'));
   await recipient.click('#tour-progress');check('customChapters',await recipient.locator('#tour-chapter option').count()===3);await recipient.selectOption('#tour-chapter',stored.stops[2].id);await arrived(recipient);report.savedCamera={expected:initial,actual:(await state(recipient)).link};check('savedCameraRestored',report.savedCamera.actual===initial);await recipient.click('#tour-exit');
   await recipient.reload();await ready(recipient);check('reloadDoesNotReplay',await recipient.locator('#trip-dialog').isHidden()&&(await state(recipient)).tour===null);
   await recipient.evaluate(()=>location.hash='stop=1:road-trip:andromeda');await arrived(recipient);check('liveStopLinkPaused',(await state(recipient)).tour.status==='paused'&&(await state(recipient)).selected.targetId==='nearby:m31');
   await share(recipient);check('copyStopAvailable',await recipient.locator('#copy-stop-button').isVisible());await recipient.click('#copy-stop-button');await recipient.waitForSelector('#share-link:visible');const stopUrl=await recipient.inputValue('#share-link');check('copyStopGrammar',stopUrl.endsWith('#stop=1:road-trip:andromeda'));await recipient.keyboard.press('Escape');
   const freshStop=await create();await freshStop.goto(stopUrl);await ready(freshStop);await arrived(freshStop);check('freshStopPaused',(await state(freshStop)).tour.status==='paused'&&await freshStop.locator('#tour-play').textContent()==='Continue');await freshStop.close();active=recipient;
   const original=(await state(recipient)).link;await recipient.evaluate(()=>location.hash='stop=1:road-trip:invented');await recipient.waitForFunction(()=>document.getElementById('toast').textContent.includes('invalid'));check('invalidStopKeepsMap',(await state(recipient)).link===original);await recipient.click('#tour-exit');
   // File imports preview before playing. Valid unknown identities fall back to the stored camera.
   await recipient.click('#tours-button');await recipient.click('#create-trip-button');await recipient.setInputFiles('#trip-file',exportPath);await recipient.waitForSelector('#trip-recipient:visible');check('fileImportPreview',await recipient.locator('#trip-preview-title').textContent()==='Our sky 🌌');
   const missing={version:1,title:'Missing identity',stops:[{id:'missing',kind:'view',name:'Stored camera',hash:'#t=10,20,30&c=1,2,3&g=nearby:missing'}]};await recipient.setInputFiles('#trip-file',{name:'missing.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(missing))});await recipient.waitForFunction(()=>document.getElementById('trip-preview-title').textContent==='Missing identity');await recipient.click('#trip-start');await arrived(recipient);await recipient.click('#tour-play');check('missingIdentityCameraOnly',(await state(recipient)).link==='#t=10,20,30&c=1,2,3'&&(await state(recipient)).selected===null);check('missingIdentityNotice',(await recipient.locator('#toast').textContent()).includes('does not contain'));await recipient.click('#tour-exit');
   // Larger valid Unicode trips use a file; no silent truncation of notes or stops.
   const long={version:1,title:'🌌'.repeat(60),stops:Array.from({length:10},(_,i)=>({id:'s'+i,kind:'view',name:'🌌'.repeat(60),note:'🌌'.repeat(180),hash:initial}))};
   await recipient.click('#tours-button');await recipient.click('#create-trip-button');await recipient.setInputFiles('#trip-file',{name:'long.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(long))});await recipient.waitForSelector('#trip-recipient:visible');await recipient.click('#trip-copy');check('longTripFileFallback',(await recipient.locator('#trip-status').textContent()).includes('too long')&&await recipient.locator('#trip-link').isHidden());
   await recipient.setInputFiles('#trip-file',{name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{bad')});await recipient.waitForFunction(()=>document.getElementById('trip-status').textContent.includes('not a supported'));check('corruptFileNotice',await recipient.locator('#trip-status').textContent().then(t=>t.includes('not a supported')));await recipient.setInputFiles('#trip-file',{name:'large.json',mimeType:'application/json',buffer:Buffer.alloc(65537,32)});check('oversizeFileNotice',await recipient.locator('#trip-status').textContent().then(t=>t.includes('64 KiB')));await recipient.click('#trip-close');
   // Context recovery pauses a running custom route and never reopens/replays its consumed invitation.
   await recipient.evaluate(h=>location.hash=h,hash({stops:stored.stops,title:stored.title,version:1}));await recipient.waitForSelector('#trip-recipient:visible');check('equivalentJsonPreview',await recipient.locator('#trip-preview-title').textContent()===stored.title);await recipient.click('#trip-start');await arrived(recipient);await recipient.evaluate(()=>{window.__loss=document.querySelector('#viewport canvas').getContext('webgl2').getExtension('WEBGL_lose_context');window.__loss.loseContext()});await recipient.waitForTimeout(250);await recipient.evaluate(()=>window.__loss.restoreContext());await recipient.waitForTimeout(1500);check('contextRecoveryPaused',(await state(recipient)).tour.status==='paused'&&await recipient.locator('#trip-dialog').isHidden());await recipient.close();
   // Blocked storage still permits editing and file/link sharing.
   const blocked=await create();await blocked.addInitScript(()=>{Storage.prototype.setItem=()=>{throw Error('blocked')}});await blocked.goto(base);await ready(blocked);await blocked.click('#tours-button');await blocked.click('#create-trip-button');await blocked.click('#trip-add');await blocked.click('#trip-save');check('blockedStorageFallback',(await blocked.locator('#trip-status').textContent()).includes('could not save'));await blocked.close();
   // Actual metadata is delayed; cancelling a custom saved-view trip must prevent a late selection/camera move.
   await creator.click('#trip-close');await creator.click('#visit-galaxy-button');await creator.fill('#galaxy-query','NGC 3982');await creator.click('#galaxy-results [role=option]');await creator.waitForFunction(()=>document.getElementById('object-name').textContent==='NGC 3982');const catalogView=(await state(creator)).link;
   const delayed=await create();let requested=false,release;const gate=new Promise(r=>release=r);await delayed.route('**/512.meta.bin',async r=>{requested=true;await gate;await r.continue().catch(()=>{})});await delayed.goto(new URL(hash({version:1,title:'Delayed destination',stops:[{id:'delayed',kind:'view',name:'NGC 3982',hash:catalogView}]}),base).href);await ready(delayed);await delayed.waitForSelector('#trip-recipient:visible');await delayed.click('#trip-start');{const deadline=Date.now()+10000;while(!requested&&Date.now()<deadline)await delayed.waitForTimeout(50)}check('lookupWasPending',requested);await delayed.keyboard.press('Escape');await delayed.click('#observer-button');await delayed.waitForTimeout(200);const held=(await state(delayed)).link;release();await delayed.waitForTimeout(1800);check('cancelledLookupCannotNavigate',(await state(delayed)).link===held&&(await state(delayed)).tour===null);await delayed.close();
   // Genuine development assets exercise an unavailable built-in custom destination.
   const subset=await create();await subset.route('**/data/catalog.json',async r=>{const response=await r.fetch(),catalog=await response.json();catalog.manifest='/data/development/manifest.json';await r.fulfill({response,json:catalog})});
   await subset.route('**/data/development/*',async r=>{const name=new URL(r.request().url()).pathname.split('/').at(-1);if(!/^[a-zA-Z0-9.-]+$/.test(name))return r.abort();await r.fulfill({body:await readFile(new URL(`../public/data/development/${name}`,import.meta.url)),contentType:name.endsWith('.json')?'application/json':'application/octet-stream'})});
   await subset.goto(new URL(hash({version:1,title:'Subset itinerary',stops:[{id:'missing',kind:'place',route:'road-trip',stop:'ngc-3982'},{id:'cloud',kind:'place',route:'road-trip',stop:'lmc'}]}),base).href);await ready(subset);await subset.waitForSelector('#trip-recipient:visible');await subset.click('#trip-start');await arrived(subset);await subset.click('#tour-play');
   check('subsetSkipsUnavailable',(await state(subset)).tour.index===1&&(await state(subset)).selected.targetId==='nearby:lmc'&&(await state(subset)).galaxies===1000000);check('subsetSkipNotice',(await subset.locator('#toast').textContent()).includes('NGC 3982')&&await subset.locator('#toast').isVisible());await subset.close();
   const pending=await create();let releaseIndex,indexRequested=false;const indexGate=new Promise(r=>releaseIndex=r);await pending.route('**/galaxy-search.json',async r=>{indexRequested=true;await indexGate;await r.continue().catch(()=>{})});await pending.goto(new URL('#stop=1:road-trip:andromeda',base).href);await ready(pending);{const deadline=Date.now()+10000;while(!indexRequested&&Date.now()<deadline)await pending.waitForTimeout(50)}check('stopWaitsForIndex',indexRequested);await pending.click('#observer-button');await pending.waitForTimeout(100);const beforeIndex=(await state(pending)).link;releaseIndex();await pending.waitForTimeout(1500);check('inputCancelsPendingStop',(await state(pending)).tour===null&&(await state(pending)).link===beforeIndex);await pending.close();
   check('catalogUnchanged',(await state(creator)).galaxies===14140375);
  }catch(error){if(active&&!active.isClosed()){await active.screenshot({path:`${dir}/failure.png`}).catch(()=>{});await writeFile(`${dir}/failure-state.json`,JSON.stringify(await active.evaluate(()=>({text:document.querySelector('#trip-dialog')?.textContent,tour:document.querySelector('#tour-status')?.textContent,hash:location.hash})),null,2))}throw error}finally{await browser.close()}
 }
 check('noPageErrors',report.errors.length===0);report.status='complete';
}catch(e){report.status='failed';report.failure=e.stack;process.exitCode=1;if(active&&!active.isClosed())await active.screenshot({path:`${dir}/failure.png`}).catch(()=>{})}
finally{clearInterval(progress);await writeFile(`${dir}/report.json`,JSON.stringify(report,null,2)+'\n');console.log(report.status,report.failure??Object.keys(report.checks).length)}
